### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by wangshuxuan123** [PC-PointClouds/mmGait_midea#1]
您好 你第一步说的json文件 是指什么呢？

**Comment by jiangSeu** [comment]
您好 这里第一步说的json文件 请问怎么理解？是指什么呢？

**Comment by jiangSeu** [comment]
您好 这里第一步说的json文件 请问怎么理解？是指什么呢？

**Comment by jiangSeu** [comment]
> 您好 你第一步说的json文件 是指什么呢？

您好 这里第一步说的json文件 请问怎么理解？是指什么呢？

**Comment by JasonYang8119** [comment]
> > 您好 你第一步说的json文件 是指什么呢？
> 
> 您好 这里第一步说的json文件 请问怎么理解？是指什么呢？

您好，这是Ti IWR系列串口输出数据，我们解析后用json格式来存储
